#ifndef PLUGIN_CLASS_FACTORY_HH
#define PLUGIN_CLASS_FACTORY_HH

// Copyright (c) 2003-2004 The University of Cincinnati.  
// All rights reserved.
// 
// UC MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
// SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
// OR NON-INFRINGEMENT.  UC SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY
// LICENSEE AS A RESULT OF USING, RESULT OF USING, MODIFYING OR DISTRIBUTING
// THIS SOFTWARE OR ITS DERIVATIVES.
// 
// By using or copying this Software, Licensee agrees to abide by the
// intellectual property laws, and all other applicable laws of the U.S.,
// and the terms of this license.
// 
// You may modify, distribute, and use the software contained in this
// package under the terms of the "GNU LIBRARY GENERAL PUBLIC LICENSE"
// version 2, June 1991. A copy of this license agreement can be found in
// the file "LGPL", distributed with this archive.
// 
// Authors: Philip A. Wilsey	philip.wilsey@ieee.org
// 	    Dale E. Martin	dmartin@cliftonlabs.com
// 
// --------------------------------------------------------------------------

#include "savant_config.hh"
#include "IRKind.hh"

REF_FORWARD_DECL(IIR_AbsoluteOperator);
REF_FORWARD_DECL(IIR_AccessSubtypeDefinition);
REF_FORWARD_DECL(IIR_AccessTypeDefinition);
REF_FORWARD_DECL(IIR_AcrossAttribute);
REF_FORWARD_DECL(IIR_ActiveAttribute);
REF_FORWARD_DECL(IIR_AdditionOperator);
REF_FORWARD_DECL(IIR_Aggregate);
REF_FORWARD_DECL(IIR_AliasDeclaration);
REF_FORWARD_DECL(IIR_Allocator);
REF_FORWARD_DECL(IIR_AndOperator);
REF_FORWARD_DECL(IIR_ArchitectureDeclaration);
REF_FORWARD_DECL(IIR_ArchitectureStatement);
REF_FORWARD_DECL(IIR_ArchitectureStatementList);
REF_FORWARD_DECL(IIR_ArrayNatureDefinition);
REF_FORWARD_DECL(IIR_ArraySubnatureDefinition);
REF_FORWARD_DECL(IIR_ArraySubtypeDefinition);
REF_FORWARD_DECL(IIR_ArrayTypeDefinition);
REF_FORWARD_DECL(IIR_AscendingAttribute);
REF_FORWARD_DECL(IIR_AssertionStatement);
REF_FORWARD_DECL(IIR_AssociationElementByExpression);
REF_FORWARD_DECL(IIR_AssociationElementOpen);
REF_FORWARD_DECL(IIR_AssociationList);
REF_FORWARD_DECL(IIR_AttributeDeclaration);
REF_FORWARD_DECL(IIR_Attribute);
REF_FORWARD_DECL(IIR_AttributeSpecification);
REF_FORWARD_DECL(IIR_AttributeSpecificationList);
REF_FORWARD_DECL(IIR_BaseAttribute);
REF_FORWARD_DECL(IIR_BitStringLiteral);
REF_FORWARD_DECL(IIR_BlockConfiguration);
REF_FORWARD_DECL(IIR_BlockStatement);
REF_FORWARD_DECL(IIR_BranchQuantityDeclaration);
REF_FORWARD_DECL(IIR_BreakElement);
REF_FORWARD_DECL(IIR_BreakStatement);
REF_FORWARD_DECL(IIR_CaseStatementAlternativeByChoices);
REF_FORWARD_DECL(IIR_CaseStatementAlternativeByExpression);
REF_FORWARD_DECL(IIR_CaseStatementAlternativeByOthers);
REF_FORWARD_DECL(IIR_CaseStatementAlternativeList);
REF_FORWARD_DECL(IIR_CaseStatement);
REF_FORWARD_DECL(IIR_CharacterLiteral);
REF_FORWARD_DECL(IIR_Choice);
REF_FORWARD_DECL(IIR_ChoiceList);
REF_FORWARD_DECL(IIR_Comment);
REF_FORWARD_DECL(IIR_CommentList);
REF_FORWARD_DECL(IIR_ComponentConfiguration);
REF_FORWARD_DECL(IIR_ComponentDeclaration);
REF_FORWARD_DECL(IIR_ComponentInstantiationStatement);
REF_FORWARD_DECL(IIR_ConcatenationOperator);
REF_FORWARD_DECL(IIR_ConcurrentAssertionStatement);
REF_FORWARD_DECL(IIR_ConcurrentBreakStatement);
REF_FORWARD_DECL(IIR_ConcurrentConditionalSignalAssignment);
REF_FORWARD_DECL(IIR_ConcurrentGenerateForStatement);
REF_FORWARD_DECL(IIR_ConcurrentGenerateIfStatement);
REF_FORWARD_DECL(IIR_ConcurrentProcedureCallStatement);
REF_FORWARD_DECL(IIR_ConcurrentSelectedSignalAssignment);
REF_FORWARD_DECL(IIR_ConcurrentStatement);
REF_FORWARD_DECL(IIR_ConditionalWaveform);
REF_FORWARD_DECL(IIR_ConditionalWaveformList);
REF_FORWARD_DECL(IIR_ConfigurationDeclaration);
REF_FORWARD_DECL(IIR_ConfigurationItem);
REF_FORWARD_DECL(IIR_ConfigurationItemList);
REF_FORWARD_DECL(IIR_ConfigurationSpecification);
REF_FORWARD_DECL(IIR_ContributionAttribute);
REF_FORWARD_DECL(IIR_ConstantDeclaration);
REF_FORWARD_DECL(IIR_ConstantInterfaceDeclaration);
REF_FORWARD_DECL(IIR_Declaration);
REF_FORWARD_DECL(IIR_DeclarationList);
REF_FORWARD_DECL(IIR_DelayedAttribute);
REF_FORWARD_DECL(IIR_DesignatorByAll);
REF_FORWARD_DECL(IIR_DesignatorByOthers);
REF_FORWARD_DECL(IIR_DesignatorExplicit);
REF_FORWARD_DECL(IIR_Designator);
REF_FORWARD_DECL(IIR_DesignatorList);
REF_FORWARD_DECL(IIR_DesignFile);
REF_FORWARD_DECL(IIR_DesignFileList);
REF_FORWARD_DECL(IIR_DesignUnitList);
REF_FORWARD_DECL(IIR_DisconnectSpecification);
REF_FORWARD_DECL(IIR_DivisionOperator);
REF_FORWARD_DECL(IIR_DotAttribute);
REF_FORWARD_DECL(IIR_DrivingAttribute);
REF_FORWARD_DECL(IIR_DrivingValueAttribute);
REF_FORWARD_DECL(IIR_DyadicOperator);
REF_FORWARD_DECL(IIR_ElementDeclaration);
REF_FORWARD_DECL(IIR_ElementDeclarationList);
REF_FORWARD_DECL(IIR_Elsif);
REF_FORWARD_DECL(IIR_EntityClassEntry);
REF_FORWARD_DECL(IIR_EntityClassEntryList);
REF_FORWARD_DECL(IIR_EntityDeclaration);
REF_FORWARD_DECL(IIR_EntityNameList);
REF_FORWARD_DECL(IIR_EnumerationLiteral);
REF_FORWARD_DECL(IIR_EnumerationLiteralList);
REF_FORWARD_DECL(IIR_EnumerationSubtypeDefinition);
REF_FORWARD_DECL(IIR_EnumerationTypeDefinition);
REF_FORWARD_DECL(IIR_EqualityOperator);
REF_FORWARD_DECL(IIR_EventAttribute);
REF_FORWARD_DECL(IIR_ExitStatement);
REF_FORWARD_DECL(IIR_ExponentiationOperator);
REF_FORWARD_DECL(IIR_Expression);
REF_FORWARD_DECL(IIR_FileDeclaration);
REF_FORWARD_DECL(IIR_FileInterfaceDeclaration);
REF_FORWARD_DECL(IIR_FileTypeDefinition);
REF_FORWARD_DECL(IIR_FloatingPointLiteral32);
REF_FORWARD_DECL(IIR_FloatingPointLiteral64);
REF_FORWARD_DECL(IIR_FloatingPointLiteral);
REF_FORWARD_DECL(IIR_FloatingSubtypeDefinition);
REF_FORWARD_DECL(IIR_FloatingTypeDefinition);
REF_FORWARD_DECL(IIR_ForLoopStatement);
REF_FORWARD_DECL(IIR_FreeQuantityDeclaration);
REF_FORWARD_DECL(IIR_FunctionCall);
REF_FORWARD_DECL(IIR_FunctionDeclaration);
REF_FORWARD_DECL(IIR_GenericList);
REF_FORWARD_DECL(IIR_GreaterThanOperator);
REF_FORWARD_DECL(IIR_GreaterThanOrEqualOperator);
REF_FORWARD_DECL(IIR_GroupConstituent);
REF_FORWARD_DECL(IIR_GroupDeclaration);
REF_FORWARD_DECL(IIR_GroupTemplateDeclaration);
REF_FORWARD_DECL(IIR);
REF_FORWARD_DECL(IIR_HighAttribute);
REF_FORWARD_DECL(IIR_Identifier);
REF_FORWARD_DECL(IIR_IdentifierList);
REF_FORWARD_DECL(IIR_IdentityOperator);
REF_FORWARD_DECL(IIR_IfStatement);
REF_FORWARD_DECL(IIR_ImageAttribute);
REF_FORWARD_DECL(IIR_IncompleteTypeDefinition);
REF_FORWARD_DECL(IIR_IndexedName);
REF_FORWARD_DECL(IIR_InequalityOperator);
REF_FORWARD_DECL(IIR_InstanceNameAttribute);
REF_FORWARD_DECL(IIR_IntegerLiteral32);
REF_FORWARD_DECL(IIR_IntegerLiteral64);
REF_FORWARD_DECL(IIR_IntegerLiteral);
REF_FORWARD_DECL(IIR_IntegerSubtypeDefinition);
REF_FORWARD_DECL(IIR_IntegerTypeDefinition);
REF_FORWARD_DECL(IIR_InterfaceDeclaration);
REF_FORWARD_DECL(IIR_InterfaceList);
REF_FORWARD_DECL(IIR_Label);
REF_FORWARD_DECL(IIR_LastActiveAttribute);
REF_FORWARD_DECL(IIR_LastEventAttribute);
REF_FORWARD_DECL(IIR_LastValueAttribute);
REF_FORWARD_DECL(IIR_LeftAttribute);
REF_FORWARD_DECL(IIR_LeftOfAttribute);
REF_FORWARD_DECL(IIR_LengthAttribute);
REF_FORWARD_DECL(IIR_LessThanOperator);
REF_FORWARD_DECL(IIR_LessThanOrEqualOperator);
REF_FORWARD_DECL(IIR_LibraryClause);
REF_FORWARD_DECL(IIR_LibraryDeclaration);
REF_FORWARD_DECL(IIR_LibraryUnit);
REF_FORWARD_DECL(IIR_LibraryUnitList);
REF_FORWARD_DECL(IIR_List);
REF_FORWARD_DECL(IIR_Literal);
REF_FORWARD_DECL(IIR_LTFAttribute);
REF_FORWARD_DECL(IIR_LowAttribute);
REF_FORWARD_DECL(IIR_ModulusOperator);
REF_FORWARD_DECL(IIR_MonadicOperator);
REF_FORWARD_DECL(IIR_MultiplicationOperator);
REF_FORWARD_DECL(IIR_Name);
REF_FORWARD_DECL(IIR_NameList);
REF_FORWARD_DECL(IIR_NandOperator);
REF_FORWARD_DECL(IIR_NatureDeclaration);
REF_FORWARD_DECL(IIR_NatureDefinition);
REF_FORWARD_DECL(IIR_NegationOperator);
REF_FORWARD_DECL(IIR_NextStatement);
REF_FORWARD_DECL(IIR_NorOperator);
REF_FORWARD_DECL(IIR_NotOperator);
REF_FORWARD_DECL(IIR_NullStatement);
REF_FORWARD_DECL(IIR_ObjectDeclaration);
REF_FORWARD_DECL(IIR_OrOperator);
REF_FORWARD_DECL(IIR_OthersInitialization);
REF_FORWARD_DECL(IIR_PackageBodyDeclaration);
REF_FORWARD_DECL(IIR_PackageDeclaration);
REF_FORWARD_DECL(IIR_PathNameAttribute);
REF_FORWARD_DECL(IIR_PhysicalLiteral);
REF_FORWARD_DECL(IIR_PhysicalSubtypeDefinition);
REF_FORWARD_DECL(IIR_PhysicalTypeDefinition);
REF_FORWARD_DECL(IIR_PhysicalUnit);
REF_FORWARD_DECL(IIR_PortList);
REF_FORWARD_DECL(IIR_PosAttribute);
REF_FORWARD_DECL(IIR_PredAttribute);
REF_FORWARD_DECL(IIR_ProcedureCallStatement);
REF_FORWARD_DECL(IIR_ProcedureDeclaration);
REF_FORWARD_DECL(IIR_ProcessStatement);
REF_FORWARD_DECL(IIR_QualifiedExpression);
REF_FORWARD_DECL(IIR_QuantityDeclaration);
REF_FORWARD_DECL(IIR_QuietAttribute);
REF_FORWARD_DECL(IIR_RangeAttribute);
REF_FORWARD_DECL(IIR_RangeTypeDefinition);
REF_FORWARD_DECL(IIR_RecordTypeDefinition);
REF_FORWARD_DECL(IIR_ReferenceAttribute);
REF_FORWARD_DECL(IIR_RemainderOperator);
REF_FORWARD_DECL(IIR_ReportStatement);
REF_FORWARD_DECL(IIR_ReturnStatement);
REF_FORWARD_DECL(IIR_ReverseRangeAttribute);
REF_FORWARD_DECL(IIR_RightAttribute);
REF_FORWARD_DECL(IIR_RightOfAttribute);
REF_FORWARD_DECL(IIR_ROLOperator);
REF_FORWARD_DECL(IIR_ROROperator);
REF_FORWARD_DECL(IIR_ScalarNatureDefinition);
REF_FORWARD_DECL(IIR_ScalarTypeDefinition);
REF_FORWARD_DECL(IIR_SelectedNameByAll);
REF_FORWARD_DECL(IIR_SelectedName);
REF_FORWARD_DECL(IIR_SelectedWaveform);
REF_FORWARD_DECL(IIR_SelectedWaveformList);
REF_FORWARD_DECL(IIR_SensitizedProcessStatement);
REF_FORWARD_DECL(IIR_SequentialStatement);
REF_FORWARD_DECL(IIR_SequentialStatementList);
REF_FORWARD_DECL(IIR_SharedVariableDeclaration);
REF_FORWARD_DECL(IIR_SignalAssignmentStatement);
REF_FORWARD_DECL(IIR_SignalDeclaration);
REF_FORWARD_DECL(IIR_SignalInterfaceDeclaration);
REF_FORWARD_DECL(IIR_Signature);
REF_FORWARD_DECL(IIR_SimpleNameAttribute);
REF_FORWARD_DECL(IIR_SimpleName);
REF_FORWARD_DECL(IIR_SimpleSimultaneousStatement);
REF_FORWARD_DECL(IIR_SimultaneousElsif);
REF_FORWARD_DECL(IIR_SimultaneousIfStatement);
REF_FORWARD_DECL(IIR_SimultaneousStatement);
REF_FORWARD_DECL(IIR_SourceQuantityDeclaration);
REF_FORWARD_DECL(IIR_SLAOperator);
REF_FORWARD_DECL(IIR_SliceName);
REF_FORWARD_DECL(IIR_SLLOperator);
REF_FORWARD_DECL(IIR_SRAOperator);
REF_FORWARD_DECL(IIR_SRLOperator);
REF_FORWARD_DECL(IIR_StableAttribute);
REF_FORWARD_DECL(IIR_Statement);
REF_FORWARD_DECL(IIR_StringLiteral);
REF_FORWARD_DECL(IIR_SubprogramDeclaration);
REF_FORWARD_DECL(IIR_SubtractionOperator);
REF_FORWARD_DECL(IIR_SubtypeDeclaration);
REF_FORWARD_DECL(IIR_SuccAttribute);
REF_FORWARD_DECL(IIR_TerminalDeclaration);
REF_FORWARD_DECL(IIR_TerminalInterfaceDeclaration);
REF_FORWARD_DECL(IIR_TextLiteral);
REF_FORWARD_DECL(IIR_ThroughAttribute);
REF_FORWARD_DECL(IIR_TransactionAttribute);
REF_FORWARD_DECL(IIR_Tuple);
REF_FORWARD_DECL(IIR_TypeConversion);
REF_FORWARD_DECL(IIR_TypeDeclaration);
REF_FORWARD_DECL(IIR_TypeDefinition);
REF_FORWARD_DECL(IIR_UnitList);
REF_FORWARD_DECL(IIR_UseClause);
REF_FORWARD_DECL(IIR_UserAttribute);
REF_FORWARD_DECL(IIR_ValAttribute);
REF_FORWARD_DECL(IIR_ValueAttribute);
REF_FORWARD_DECL(IIR_VariableAssignmentStatement);
REF_FORWARD_DECL(IIR_VariableDeclaration);
REF_FORWARD_DECL(IIR_VariableInterfaceDeclaration);
REF_FORWARD_DECL(IIR_WaitStatement);
REF_FORWARD_DECL(IIR_WaveformElement);
REF_FORWARD_DECL(IIR_WaveformList);
REF_FORWARD_DECL(IIR_WhileLoopStatement);
REF_FORWARD_DECL(IIR_XnorOperator);
REF_FORWARD_DECL(IIR_XorOperator);
REF_FORWARD_DECL(IIR_ZTFAttribute);
REF_FORWARD_DECL(StandardPackage);

/** Interface version of the plugin class factory.  This provides an interface which is then implemented for
    each plugin, and allows the system to create AIRE node for that extension without knowing the specific details */
class plugin_class_factory {
public:
  /** Returns the standard package singleton for this plugin type. */
  virtual StandardPackageRef get_standard_package() = 0;

  /** @name Create nodes
      Methods for creating specific nodes
  */
  //@{
  /** Returns the new class based on the passed in IIR_Kind type. */
  virtual IIRRef get_new_class(IIR_Kind) = 0;

  virtual IIR_AbsoluteOperatorRef                          new_IIR_AbsoluteOperator() = 0;
  virtual IIR_AccessSubtypeDefinitionRef                   new_IIR_AccessSubtypeDefinition() = 0;
  virtual IIR_AccessTypeDefinitionRef                      new_IIR_AccessTypeDefinition() = 0;
  virtual IIR_AcrossAttributeRef                           new_IIR_AcrossAttribute() = 0;
  virtual IIR_ActiveAttributeRef                           new_IIR_ActiveAttribute() = 0;
  virtual IIR_AdditionOperatorRef                          new_IIR_AdditionOperator() = 0;
  virtual IIR_AggregateRef                                 new_IIR_Aggregate() = 0;
  virtual IIR_AliasDeclarationRef                          new_IIR_AliasDeclaration() = 0;
  virtual IIR_AllocatorRef                                 new_IIR_Allocator() = 0;
  virtual IIR_AndOperatorRef                               new_IIR_AndOperator() = 0;
  virtual IIR_ArchitectureDeclarationRef                   new_IIR_ArchitectureDeclaration() = 0;
  virtual IIR_ArchitectureStatementRef                     new_IIR_ArchitectureStatement() = 0;
  virtual IIR_ArchitectureStatementListRef                 new_IIR_ArchitectureStatementList() = 0;
  virtual IIR_ArrayNatureDefinitionRef                     new_IIR_ArrayNatureDefinition() = 0;
  virtual IIR_ArraySubnatureDefinitionRef                  new_IIR_ArraySubnatureDefinition() = 0;
  virtual IIR_ArraySubtypeDefinitionRef                    new_IIR_ArraySubtypeDefinition() = 0;
  virtual IIR_ArrayTypeDefinitionRef                       new_IIR_ArrayTypeDefinition() = 0;
  virtual IIR_AscendingAttributeRef                        new_IIR_AscendingAttribute() = 0;
  virtual IIR_AssertionStatementRef                        new_IIR_AssertionStatement() = 0;
  virtual IIR_AssociationElementByExpressionRef            new_IIR_AssociationElementByExpression() = 0;
  virtual IIR_AssociationElementOpenRef                    new_IIR_AssociationElementOpen() = 0;
  virtual IIR_AssociationListRef                           new_IIR_AssociationList() = 0;
  virtual IIR_AttributeDeclarationRef                      new_IIR_AttributeDeclaration() = 0;
  virtual IIR_AttributeSpecificationRef                    new_IIR_AttributeSpecification() = 0;
  virtual IIR_AttributeSpecificationListRef                new_IIR_AttributeSpecificationList() = 0;
  virtual IIR_BaseAttributeRef                             new_IIR_BaseAttribute() = 0;
  virtual IIR_BitStringLiteralRef                          new_IIR_BitStringLiteral() = 0;
  virtual IIR_BlockConfigurationRef                        new_IIR_BlockConfiguration() = 0;
  virtual IIR_BlockStatementRef                            new_IIR_BlockStatement() = 0;
  virtual IIR_BranchQuantityDeclarationRef                 new_IIR_BranchQuantityDeclaration() = 0;
  virtual IIR_BreakElementRef                              new_IIR_BreakElement() = 0;
  virtual IIR_BreakStatementRef                            new_IIR_BreakStatement() = 0;
  virtual IIR_CaseStatementAlternativeByChoicesRef         new_IIR_CaseStatementAlternativeByChoices() = 0;
  virtual IIR_CaseStatementAlternativeByExpressionRef      new_IIR_CaseStatementAlternativeByExpression() = 0;
  virtual IIR_CaseStatementAlternativeByOthersRef          new_IIR_CaseStatementAlternativeByOthers() = 0;
  virtual IIR_CaseStatementAlternativeListRef              new_IIR_CaseStatementAlternativeList() = 0;
  virtual IIR_CaseStatementRef                             new_IIR_CaseStatement() = 0;
  virtual IIR_CharacterLiteralRef                          new_IIR_CharacterLiteral() = 0;
  virtual IIR_ChoiceRef                                    new_IIR_Choice() = 0;
  virtual IIR_ChoiceListRef                                new_IIR_ChoiceList() = 0;
  virtual IIR_CommentRef                                   new_IIR_Comment() = 0;
  virtual IIR_CommentListRef                               new_IIR_CommentList() = 0;
  virtual IIR_ComponentConfigurationRef                    new_IIR_ComponentConfiguration() = 0;
  virtual IIR_ComponentDeclarationRef                      new_IIR_ComponentDeclaration() = 0;
  virtual IIR_ComponentInstantiationStatementRef           new_IIR_ComponentInstantiationStatement() = 0;
  virtual IIR_ConcatenationOperatorRef                     new_IIR_ConcatenationOperator() = 0;
  virtual IIR_ConcurrentAssertionStatementRef              new_IIR_ConcurrentAssertionStatement() = 0;
  virtual IIR_ConcurrentBreakStatementRef                  new_IIR_ConcurrentBreakStatement() = 0;
  virtual IIR_ConcurrentConditionalSignalAssignmentRef     new_IIR_ConcurrentConditionalSignalAssignment() = 0;
  virtual IIR_ConcurrentGenerateForStatementRef            new_IIR_ConcurrentGenerateForStatement() = 0;
  virtual IIR_ConcurrentGenerateIfStatementRef             new_IIR_ConcurrentGenerateIfStatement() = 0;
  virtual IIR_ConcurrentProcedureCallStatementRef          new_IIR_ConcurrentProcedureCallStatement() = 0;
  virtual IIR_ConcurrentSelectedSignalAssignmentRef        new_IIR_ConcurrentSelectedSignalAssignment() = 0;
  virtual IIR_ConditionalWaveformRef                       new_IIR_ConditionalWaveform() = 0;
  virtual IIR_ConditionalWaveformListRef                   new_IIR_ConditionalWaveformList() = 0;
  virtual IIR_ConfigurationDeclarationRef                  new_IIR_ConfigurationDeclaration() = 0;
  virtual IIR_ConfigurationItemRef                         new_IIR_ConfigurationItem() = 0;
  virtual IIR_ConfigurationItemListRef                     new_IIR_ConfigurationItemList() = 0;
  virtual IIR_ConfigurationSpecificationRef                new_IIR_ConfigurationSpecification() = 0;
  virtual IIR_ContributionAttributeRef                     new_IIR_ContributionAttribute() = 0;
  virtual IIR_ConstantDeclarationRef                       new_IIR_ConstantDeclaration() = 0;
  virtual IIR_ConstantInterfaceDeclarationRef              new_IIR_ConstantInterfaceDeclaration() = 0;
  virtual IIR_DeclarationListRef                           new_IIR_DeclarationList() = 0;
  virtual IIR_DelayedAttributeRef                          new_IIR_DelayedAttribute() = 0;
  virtual IIR_DesignatorByAllRef                           new_IIR_DesignatorByAll() = 0;
  virtual IIR_DesignatorByOthersRef                        new_IIR_DesignatorByOthers() = 0;
  virtual IIR_DesignatorExplicitRef                        new_IIR_DesignatorExplicit() = 0;
  virtual IIR_DesignatorRef                                new_IIR_Designator() = 0;
  virtual IIR_DesignatorListRef                            new_IIR_DesignatorList() = 0;
  virtual IIR_DesignFileRef                                new_IIR_DesignFile() = 0;
  virtual IIR_DesignFileListRef                            new_IIR_DesignFileList() = 0;
  virtual IIR_DesignUnitListRef                            new_IIR_DesignUnitList() = 0;
  virtual IIR_DisconnectSpecificationRef                   new_IIR_DisconnectSpecification() = 0;
  virtual IIR_DivisionOperatorRef                          new_IIR_DivisionOperator() = 0;
  virtual IIR_DotAttributeRef                              new_IIR_DotAttribute() = 0;
  virtual IIR_DrivingAttributeRef                          new_IIR_DrivingAttribute() = 0;
  virtual IIR_DrivingValueAttributeRef                     new_IIR_DrivingValueAttribute() = 0;
  virtual IIR_ElementDeclarationRef                        new_IIR_ElementDeclaration() = 0;
  virtual IIR_ElementDeclarationListRef                    new_IIR_ElementDeclarationList() = 0;
  virtual IIR_ElsifRef                                     new_IIR_Elsif() = 0;
  virtual IIR_EntityClassEntryRef                          new_IIR_EntityClassEntry() = 0;
  virtual IIR_EntityClassEntryListRef                      new_IIR_EntityClassEntryList() = 0;
  virtual IIR_EntityDeclarationRef                         new_IIR_EntityDeclaration() = 0;
  virtual IIR_EntityNameListRef                            new_IIR_EntityNameList() = 0;
  virtual IIR_EnumerationLiteralRef                        new_IIR_EnumerationLiteral() = 0;
  virtual IIR_EnumerationLiteralListRef                    new_IIR_EnumerationLiteralList() = 0;
  virtual IIR_EnumerationSubtypeDefinitionRef              new_IIR_EnumerationSubtypeDefinition() = 0;
  virtual IIR_EnumerationTypeDefinitionRef                 new_IIR_EnumerationTypeDefinition() = 0;
  virtual IIR_EqualityOperatorRef                          new_IIR_EqualityOperator() = 0;
  virtual IIR_EventAttributeRef                            new_IIR_EventAttribute() = 0;
  virtual IIR_ExitStatementRef                             new_IIR_ExitStatement() = 0;
  virtual IIR_ExponentiationOperatorRef                    new_IIR_ExponentiationOperator() = 0;
  virtual IIR_FileDeclarationRef                           new_IIR_FileDeclaration() = 0;
  virtual IIR_FileInterfaceDeclarationRef                  new_IIR_FileInterfaceDeclaration() = 0;
  virtual IIR_FileTypeDefinitionRef                        new_IIR_FileTypeDefinition() = 0;
  virtual IIR_FloatingPointLiteral32Ref                    new_IIR_FloatingPointLiteral32() = 0;
  virtual IIR_FloatingPointLiteral64Ref                    new_IIR_FloatingPointLiteral64() = 0;
  virtual IIR_FloatingPointLiteralRef                      new_IIR_FloatingPointLiteral() = 0;
  virtual IIR_FloatingSubtypeDefinitionRef                 new_IIR_FloatingSubtypeDefinition() = 0;
  virtual IIR_FloatingTypeDefinitionRef                    new_IIR_FloatingTypeDefinition() = 0;
  virtual IIR_ForLoopStatementRef                          new_IIR_ForLoopStatement() = 0;
  virtual IIR_FreeQuantityDeclarationRef                   new_IIR_FreeQuantityDeclaration() = 0;
  virtual IIR_FunctionCallRef                              new_IIR_FunctionCall() = 0;
  virtual IIR_FunctionDeclarationRef                       new_IIR_FunctionDeclaration() = 0;
  virtual IIR_GenericListRef                               new_IIR_GenericList() = 0;
  virtual IIR_GreaterThanOperatorRef                       new_IIR_GreaterThanOperator() = 0;
  virtual IIR_GreaterThanOrEqualOperatorRef                new_IIR_GreaterThanOrEqualOperator() = 0;
  virtual IIR_GroupConstituentRef                          new_IIR_GroupConstituent() = 0;
  virtual IIR_GroupDeclarationRef                          new_IIR_GroupDeclaration() = 0;
  virtual IIR_GroupTemplateDeclarationRef                  new_IIR_GroupTemplateDeclaration() = 0;
  virtual IIR_HighAttributeRef                             new_IIR_HighAttribute() = 0;
  virtual IIR_IdentifierRef                                new_IIR_Identifier() = 0;
  virtual IIR_IdentifierListRef                            new_IIR_IdentifierList() = 0;
  virtual IIR_IdentityOperatorRef                          new_IIR_IdentityOperator() = 0;
  virtual IIR_IfStatementRef                               new_IIR_IfStatement() = 0;
  virtual IIR_ImageAttributeRef                            new_IIR_ImageAttribute() = 0;
  virtual IIR_IncompleteTypeDefinitionRef                  new_IIR_IncompleteTypeDefinition() = 0;
  virtual IIR_IndexedNameRef                               new_IIR_IndexedName() = 0;
  virtual IIR_InequalityOperatorRef                        new_IIR_InequalityOperator() = 0;
  virtual IIR_InstanceNameAttributeRef                     new_IIR_InstanceNameAttribute() = 0;
  virtual IIR_IntegerLiteral32Ref                          new_IIR_IntegerLiteral32() = 0;
  virtual IIR_IntegerLiteral64Ref                          new_IIR_IntegerLiteral64() = 0;
  virtual IIR_IntegerLiteralRef                            new_IIR_IntegerLiteral() = 0;
  virtual IIR_IntegerSubtypeDefinitionRef                  new_IIR_IntegerSubtypeDefinition() = 0;
  virtual IIR_IntegerTypeDefinitionRef                     new_IIR_IntegerTypeDefinition() = 0;
  virtual IIR_InterfaceListRef                             new_IIR_InterfaceList() = 0;
  virtual IIR_LabelRef                                     new_IIR_Label() = 0;
  virtual IIR_LastActiveAttributeRef                       new_IIR_LastActiveAttribute() = 0;
  virtual IIR_LastEventAttributeRef                        new_IIR_LastEventAttribute() = 0;
  virtual IIR_LastValueAttributeRef                        new_IIR_LastValueAttribute() = 0;
  virtual IIR_LeftAttributeRef                             new_IIR_LeftAttribute() = 0;
  virtual IIR_LeftOfAttributeRef                           new_IIR_LeftOfAttribute() = 0;
  virtual IIR_LengthAttributeRef                           new_IIR_LengthAttribute() = 0;
  virtual IIR_LessThanOperatorRef                          new_IIR_LessThanOperator() = 0;
  virtual IIR_LessThanOrEqualOperatorRef                   new_IIR_LessThanOrEqualOperator() = 0;
  virtual IIR_LibraryClauseRef                             new_IIR_LibraryClause() = 0;
  virtual IIR_LibraryDeclarationRef                        new_IIR_LibraryDeclaration() = 0;
  virtual IIR_LibraryUnitListRef                           new_IIR_LibraryUnitList() = 0;
  virtual IIR_LiteralRef                                   new_IIR_Literal() = 0;
  virtual IIR_LowAttributeRef                              new_IIR_LowAttribute() = 0;
  virtual IIR_LTFAttributeRef                              new_IIR_LTFAttribute() = 0;
  virtual IIR_ModulusOperatorRef                           new_IIR_ModulusOperator() = 0;
  virtual IIR_MultiplicationOperatorRef                    new_IIR_MultiplicationOperator() = 0;
  virtual IIR_NameRef                                      new_IIR_Name() = 0;
  virtual IIR_NameListRef                                  new_IIR_NameList() = 0;
  virtual IIR_NandOperatorRef                              new_IIR_NandOperator() = 0;
  virtual IIR_NatureDeclarationRef                         new_IIR_NatureDeclaration() = 0;
  virtual IIR_NatureDefinitionRef                          new_IIR_NatureDefinition() = 0;
  virtual IIR_NegationOperatorRef                          new_IIR_NegationOperator() = 0;
  virtual IIR_NextStatementRef                             new_IIR_NextStatement() = 0;
  virtual IIR_NorOperatorRef                               new_IIR_NorOperator() = 0;
  virtual IIR_NotOperatorRef                               new_IIR_NotOperator() = 0;
  virtual IIR_NullStatementRef                             new_IIR_NullStatement() = 0;
  virtual IIR_OrOperatorRef                                new_IIR_OrOperator() = 0;
  virtual IIR_OthersInitializationRef                      new_IIR_OthersInitialization() = 0;
  virtual IIR_PackageBodyDeclarationRef                    new_IIR_PackageBodyDeclaration() = 0;
  virtual IIR_PackageDeclarationRef                        new_IIR_PackageDeclaration() = 0;
  virtual IIR_PathNameAttributeRef                         new_IIR_PathNameAttribute() = 0;
  virtual IIR_PhysicalLiteralRef                           new_IIR_PhysicalLiteral() = 0;
  virtual IIR_PhysicalSubtypeDefinitionRef                 new_IIR_PhysicalSubtypeDefinition() = 0;
  virtual IIR_PhysicalTypeDefinitionRef                    new_IIR_PhysicalTypeDefinition() = 0;
  virtual IIR_PhysicalUnitRef                              new_IIR_PhysicalUnit() = 0;
  virtual IIR_PortListRef                                  new_IIR_PortList() = 0;
  virtual IIR_PosAttributeRef                              new_IIR_PosAttribute() = 0;
  virtual IIR_PredAttributeRef                             new_IIR_PredAttribute() = 0;
  virtual IIR_ProcedureCallStatementRef                    new_IIR_ProcedureCallStatement() = 0;
  virtual IIR_ProcedureDeclarationRef                      new_IIR_ProcedureDeclaration() = 0;
  virtual IIR_ProcessStatementRef                          new_IIR_ProcessStatement() = 0;
  virtual IIR_QualifiedExpressionRef                       new_IIR_QualifiedExpression() = 0;
  virtual IIR_QuantityDeclarationRef                       new_IIR_QuantityDeclaration() = 0;
  virtual IIR_QuietAttributeRef                            new_IIR_QuietAttribute() = 0;
  virtual IIR_RangeAttributeRef                            new_IIR_RangeAttribute() = 0;
  virtual IIR_RangeTypeDefinitionRef                       new_IIR_RangeTypeDefinition() = 0;
  virtual IIR_RecordTypeDefinitionRef                      new_IIR_RecordTypeDefinition() = 0;
  virtual IIR_ReferenceAttributeRef                        new_IIR_ReferenceAttribute() = 0;
  virtual IIR_RemainderOperatorRef                         new_IIR_RemainderOperator() = 0;
  virtual IIR_ReportStatementRef                           new_IIR_ReportStatement() = 0;
  virtual IIR_ReturnStatementRef                           new_IIR_ReturnStatement() = 0;
  virtual IIR_ReverseRangeAttributeRef                     new_IIR_ReverseRangeAttribute() = 0;
  virtual IIR_RightAttributeRef                            new_IIR_RightAttribute() = 0;
  virtual IIR_RightOfAttributeRef                          new_IIR_RightOfAttribute() = 0;
  virtual IIR_ROLOperatorRef                               new_IIR_ROLOperator() = 0;
  virtual IIR_ROROperatorRef                               new_IIR_ROROperator() = 0;
  virtual IIR_ScalarNatureDefinitionRef                    new_IIR_ScalarNatureDefinition() = 0;
  virtual IIR_SelectedNameByAllRef                         new_IIR_SelectedNameByAll() = 0;
  virtual IIR_SelectedNameRef                              new_IIR_SelectedName() = 0;
  virtual IIR_SelectedWaveformRef                          new_IIR_SelectedWaveform() = 0;
  virtual IIR_SelectedWaveformListRef                      new_IIR_SelectedWaveformList() = 0;
  virtual IIR_SensitizedProcessStatementRef                new_IIR_SensitizedProcessStatement() = 0;
  virtual IIR_SequentialStatementListRef                   new_IIR_SequentialStatementList() = 0;
  virtual IIR_SharedVariableDeclarationRef                 new_IIR_SharedVariableDeclaration() = 0;
  virtual IIR_SignalAssignmentStatementRef                 new_IIR_SignalAssignmentStatement() = 0;
  virtual IIR_SignalDeclarationRef                         new_IIR_SignalDeclaration() = 0;
  virtual IIR_SignalInterfaceDeclarationRef                new_IIR_SignalInterfaceDeclaration() = 0;
  virtual IIR_SignatureRef                                 new_IIR_Signature() = 0;
  virtual IIR_SimpleNameAttributeRef                       new_IIR_SimpleNameAttribute() = 0;
  virtual IIR_SimpleNameRef                                new_IIR_SimpleName() = 0;
  virtual IIR_SimpleSimultaneousStatementRef               new_IIR_SimpleSimultaneousStatement() = 0;
  virtual IIR_SimultaneousElsifRef                         new_IIR_SimultaneousElsif() = 0;
  virtual IIR_SimultaneousIfStatementRef                   new_IIR_SimultaneousIfStatement() = 0;
  virtual IIR_SLAOperatorRef                               new_IIR_SLAOperator() = 0;
  virtual IIR_SliceNameRef                                 new_IIR_SliceName() = 0;
  virtual IIR_SLLOperatorRef                               new_IIR_SLLOperator() = 0;
  virtual IIR_SourceQuantityDeclarationRef                 new_IIR_SourceQuantityDeclaration() = 0;
  virtual IIR_SRAOperatorRef                               new_IIR_SRAOperator() = 0;
  virtual IIR_SRLOperatorRef                               new_IIR_SRLOperator() = 0;
  virtual IIR_StableAttributeRef                           new_IIR_StableAttribute() = 0;
  virtual IIR_StringLiteralRef                             new_IIR_StringLiteral() = 0;
  virtual IIR_SubprogramDeclarationRef                     new_IIR_SubprogramDeclaration() = 0;
  virtual IIR_SubtractionOperatorRef                       new_IIR_SubtractionOperator() = 0;
  virtual IIR_SubtypeDeclarationRef                        new_IIR_SubtypeDeclaration() = 0;
  virtual IIR_SuccAttributeRef                             new_IIR_SuccAttribute() = 0;
  virtual IIR_TerminalDeclarationRef                       new_IIR_TerminalDeclaration() = 0;
  virtual IIR_TerminalInterfaceDeclarationRef              new_IIR_TerminalInterfaceDeclaration() = 0;
  virtual IIR_TextLiteralRef                               new_IIR_TextLiteral() = 0;
  virtual IIR_ThroughAttributeRef                          new_IIR_ThroughAttribute() = 0;
  virtual IIR_TransactionAttributeRef                      new_IIR_TransactionAttribute() = 0;
  virtual IIR_TupleRef                                     new_IIR_Tuple() = 0;
  virtual IIR_TypeConversionRef                            new_IIR_TypeConversion() = 0;
  virtual IIR_TypeDeclarationRef                           new_IIR_TypeDeclaration() = 0;
  virtual IIR_UnitListRef                                  new_IIR_UnitList() = 0;
  virtual IIR_UseClauseRef                                 new_IIR_UseClause() = 0;
  virtual IIR_UserAttributeRef                             new_IIR_UserAttribute() = 0;
  virtual IIR_ValAttributeRef                              new_IIR_ValAttribute() = 0;
  virtual IIR_ValueAttributeRef                            new_IIR_ValueAttribute() = 0;
  virtual IIR_VariableAssignmentStatementRef               new_IIR_VariableAssignmentStatement() = 0;
  virtual IIR_VariableDeclarationRef                       new_IIR_VariableDeclaration() = 0;
  virtual IIR_VariableInterfaceDeclarationRef              new_IIR_VariableInterfaceDeclaration() = 0;
  virtual IIR_WaitStatementRef                             new_IIR_WaitStatement() = 0;
  virtual IIR_WaveformElementRef                           new_IIR_WaveformElement() = 0;
  virtual IIR_WaveformListRef                              new_IIR_WaveformList() = 0;
  virtual IIR_WhileLoopStatementRef                        new_IIR_WhileLoopStatement() = 0;
  virtual IIR_XnorOperatorRef                              new_IIR_XnorOperator() = 0;
  virtual IIR_XorOperatorRef                               new_IIR_XorOperator() = 0;
  virtual IIR_ZTFAttributeRef                              new_IIR_ZTFAttribute() = 0;
  //@}

private:
  friend class IIRBase;
  /** When cloning the StandardPackage, we do really need to allocate a new
      one, and not just access a singleton.  This method allows for
      this. */
  virtual StandardPackageRef new_StandardPackage() = 0; 
};
#endif
